name: slack-pr-notify

on:
  pull_request_target:
    types: [assigned, opened, reopened]
    branches:
      - master

jobs:
  slack-pr-notify:
    runs-on: ubuntu-latest
    env:
      # https://securitylab.github.com/research/github-actions-untrusted-input/#Remediation
      PR_TITLE: ${{ github.event.issue.title }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - run: |
          curl -X POST \
          -H 'Content-type: application/json' \
          --data "{\"text\":\"$PR_AUTHOR opened merge request [$PR_TITLE] on $PR_URL\"}" ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
