name: slash-command-dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.BOT_ACCOUNT_GITHUB_TOKEN }}
          dispatch-type: repository
          issue-type: pull-request
          reaction-type: eyes
          permission: |
            write
          commands: |
            update
            release
